title: Test GitHub Pages
author: dziembienski
email: daniel.ziembienski@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The awesome description of this new site is here! 
  
  You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
